/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BrandHallRouteImport } from './routes/brand-hall'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as PioneerRouteImport } from './routes/pioneer'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as StackRouteImport } from './routes/stack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandHallRoute = BrandHallRouteImport.update({
  id: '/brand-hall',
  path: '/brand-hall',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PioneerRoute = PioneerRouteImport.update({
  id: '/pioneer',
  path: '/pioneer',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/brand-hall': typeof BrandHallRoute
  '/documents': typeof DocumentsRoute
  '/pioneer': typeof PioneerRoute
  '/plans': typeof PlansRoute
  '/portfolio': typeof PortfolioRoute
  '/stack': typeof StackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/brand-hall': typeof BrandHallRoute
  '/documents': typeof DocumentsRoute
  '/pioneer': typeof PioneerRoute
  '/plans': typeof PlansRoute
  '/portfolio': typeof PortfolioRoute
  '/stack': typeof StackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/brand-hall': typeof BrandHallRoute
  '/documents': typeof DocumentsRoute
  '/pioneer': typeof PioneerRoute
  '/plans': typeof PlansRoute
  '/portfolio': typeof PortfolioRoute
  '/stack': typeof StackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/brand-hall'
    | '/documents'
    | '/pioneer'
    | '/plans'
    | '/portfolio'
    | '/stack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/brand-hall'
    | '/documents'
    | '/pioneer'
    | '/plans'
    | '/portfolio'
    | '/stack'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/brand-hall'
    | '/documents'
    | '/pioneer'
    | '/plans'
    | '/portfolio'
    | '/stack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BrandHallRoute: typeof BrandHallRoute
  DocumentsRoute: typeof DocumentsRoute
  PioneerRoute: typeof PioneerRoute
  PlansRoute: typeof PlansRoute
  PortfolioRoute: typeof PortfolioRoute
  StackRoute: typeof StackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-hall': {
      id: '/brand-hall'
      path: '/brand-hall'
      fullPath: '/brand-hall'
      preLoaderRoute: typeof BrandHallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pioneer': {
      id: '/pioneer'
      path: '/pioneer'
      fullPath: '/pioneer'
      preLoaderRoute: typeof PioneerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BrandHallRoute: BrandHallRoute,
  DocumentsRoute: DocumentsRoute,
  PioneerRoute: PioneerRoute,
  PlansRoute: PlansRoute,
  PortfolioRoute: PortfolioRoute,
  StackRoute: StackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
